import type { NextPage } from "next";
import data from "../lib/data.json";
import Head from "next/head";
import Link from "next/link";
import { Navbar } from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Galleria SlideShow Site</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Navbar />
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <div className="grid grid-cols-1 gap-y-[23px]">
          {data.map(({ name, images }, index) => (
            <Link
              key={index}
              href={`/paint/${name.replace(/\s/g, "").toLowerCase()}`}
            >
              {/* eslint-disable-next-line @next/next/no-img-element */}
              <img src={images.thumbnail} alt={name} />
            </Link>
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
