import type { NextPage } from "next";
import data from "../lib/data.json";
import Image from "next/image";
import Head from "next/head";
import { Navbar } from "../components/Navbar";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Galleria SlideShow Site</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Navbar />
      <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
        <div className="grid grid-cols-1 gap-y-[24px]">
          {data.map(({ name, images }, index) => (
            <Image
              key={index}
              src={images.thumbnail}
              alt={name}
              height="100%"
              width="100%"
            />
          ))}
        </div>
      </main>
    </>
  );
};

export default Home;
