import type { NextPage } from "next";
import Head from "next/head";

const Home: NextPage = () => {
  return (
    <>
      <Head>
        <title>Galleria SlideShow Site</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <body>
        <main className="container mx-auto flex flex-col items-center justify-center min-h-screen p-4">
          <h1>Tests for font</h1>
        </main>
      </body>
    </>
  );
};

export default Home;
