import type { NextPage } from 'next'
import Head from 'next/head'
import { Carousel } from '../components/Carousel'
import { Navbar } from '../components/Navbar/Navbar'
import { Searchbar } from '../components/Searchbar'

const Home: NextPage = () => {
    return (
        <>
            <Head>
                <title>Frontend Mentor | Entertainment web app</title>
                <meta name="description" content="Generated by create-t3-app" />
                <link rel="icon" href="assets/favicon-32x32.png" />
            </Head>
            <Searchbar />
            <Navbar />
            <Carousel />
        </>
    )
}

export default Home
