import Head from "next/head";
import { paints } from "../../data/data";
import { Navbar } from "../../components/Navbar";
import { GetStaticProps, InferGetStaticPropsType } from "next";

export const getStaticProps: GetStaticProps = async ({ params }) => {
  const paint = paints.filter((p) => p.id.toString() === params?.id);
  return {
    props: {
      allPaintsData: paint[0],
    },
  };
};

export const getStaticPaths = async () => {
  const paths = paints.map((paint) => ({
    params: { id: paint.id.toString() },
  }));
  return { paths, fallback: false };
};

const Paint = ({
  allPaintsData,
}: InferGetStaticPropsType<typeof getStaticProps>) => {
  return (
    <>
      <Head>
        <title>Galleria SlideShow Site</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Navbar />
      <main>
        <h1>This the page for {allPaintsData.description}</h1>
      </main>
    </>
  );
};

export default Paint;
