import { useRouter } from "next/router";
import data from "../../lib/data.json";
import Head from "next/head";
import { Navbar } from "../components/Navbar";

export type PaintsData = Root[];

export interface Root {
  name: string;
  year: number;
  description: string;
  source: string;
  artist: Artist;
  images: Images;
}

export interface Artist {
  image: string;
  name: string;
}

export interface Images {
  thumbnail: string;
  hero: Hero;
  gallery: string;
}

export interface Hero {
  small: string;
  large: string;
}

const Paint = () => {
  const router = useRouter();
  const { pid } = router.query;

  return (
    <>
      <Head>
        <title>Galleria SlideShow Site</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Navbar />
      <main>
        <h1>This the page for {pid}</h1>
      </main>
    </>
  );
};

export default Paint;
