import Head from "next/head";
import { paints } from "../../data/data";
import { Navbar } from "../../components/Navbar";
import { useRouter } from "next/router";
import { GetStaticProps } from "next";

export const getStaticProps: GetStaticProps = async () => {
  return {
    props: {
      allPaintsData: paints,
    },
  };
};

const Paint = () => {
  const router = useRouter();
  const { name } = router.query;
  return (
    <>
      <Head>
        <title>Galleria SlideShow Site</title>
        <meta name="description" content="Generated by create-t3-app" />
        <link rel="icon" href="/favicon-32x32.png" />
      </Head>
      <Navbar />
      <main>
        <h1>This the page for {name}</h1>
      </main>
    </>
  );
};

export default Paint;
